export const listProjets = [
  {
    id: 1,
    img: "../assets/proj1.jpg",
    title: "CandiMate App",
    summary:
      "CandiMate vise à simplifier ce processus en offrant une solution centralisée permettant de suivre les postulations, de personnaliser le contenu (lettres de motivation, messages LinkedIn) et d'optimiser la recherche d'emploi. L’application aidera à organiser les démarches et augmentera les chances de succès des utilisateurs.",
    desc: "Une application web qui permet aux demandeurs d'emploi de gérer leurs candidatures à des offres d'emploi de manière efficace.",
    content: [
      "CandiMate est une application web qui permet aux demandeurs d'emploi de gérer leurs candidatures à des offres d'emploi, de créer et d’envoyer des lettres de motivation personnalisées, et de générer des messages d'accroche LinkedIn. Les utilisateurs pourront suivre l'évolution de leurs candidatures via un tableau de bord kanban, représentant visuellement chaque étape du processus (à postuler, en attente, entretien, accepté, refusé). L'intégration de l'API Gemini permettra de générer automatiquement des lettres de motivation personnalisées, augmentant ainsi l'efficacité des utilisateurs.",
      "Le système comprend une gestion complète des utilisateurs avec authentification, et stocke les données dans une base MySQL avec des relations entre les entités User, JobOffer, CoverLetter et LinkedInMessage.",
      "L'architecture suit le modèle MVC de Symfony avec des contrôleurs dédiés pour chaque fonctionnalité, des entités Doctrine pour la persistance des données, et utilise des énumérations PHP pour gérer les statuts des offres d'emploi.",
      "N'hésitez pas à consulter le projet en visitant le lien du projet.",
    ],
    technologies: [
      "Symfony7",
      "Twig",
      "Tailwind",
      "MySQL",
      "API Gemini ",
      "JavaScript",
      "GIT",
      "Github",
    ],
    projectLink: "https://github.com/LeaBouillot/CandiMate.git",
    site: "https://candimate.leabouillot.top",
  },
  {
    id: 2,
    img: "../assets/proj2.png",
    title: "Hall4Hall App",
    summary:
      "C'est une application web pour la gestion des réservations de salles, permettant aux utilisateurs de consulter la disponibilité des espaces, de réserver en ligne et de gérer leurs réservations de manière autonome. Elle facilite également le travail des administrateurs en offrant un outil centralisé pour suivre et gérer les réservations, ainsi que pour gérer les conflits ou les ajustements nécessaires.",
    desc: "Une application web pour la gestion des réservations de salles, permettant aux utilisateurs de consulter la disponibilité des espaces, de réserver en ligne et de gérer leurs réservations de manière autonome.",
    content: [
      "Le projet vise à créer une application web permettant la gestion des réservations de salles pour une organisation (entreprise, association, etc.). L'objectif principal est de permettre aux utilisateurs de réserver des salles en fonction de leurs besoins et de simplifier le processus de gestion pour les administrateurs.",
      "Un visiteur pourra s'inscrire et, après son inscription, accéder à un visuel des salles existantes. Il pourra ensuite effectuer une recherche ciblée et obtenir des résultats présentant les salles correspondant à ses critères. Il pourra également consulter les disponibilités d'une salle et effectuer une demande de pré-réservation.",
      "L'administrateur aura accès à un tableau de bord (Dashboard) lui permettant de consulter, créer, modifier et supprimer les réservations, ainsi que de configurer les salles, les équipements et les critères d'ergonomie directement depuis la base de données.",
      "L'administrateur devra valider ou annuler les demandes de réservation faites par les utilisateurs.",
      "N'hésitez pas à consulter le projet en visitant le lien du projet.",
    ],
    technologies: ["Symfony7", "JavaScript", "Api Stripe", "GIT", "Github"],
    projectLink: "https://github.com/LeaBouillot/Hall4All_Symfony7.git",
    site: "https://hall.hall4all.fr",
  },
  {
    id: 3,
    img: "../assets/proj3.png",
    title: "Portfolio Léa",
    summary:
    "Mon Portfolio présente une sélection de mes projets personnels, mettant en valeur mes compétences techniques et créatives. Chaque projet inclut une étude de cas détaillée pour mieux comprendre le processus de création et les technologies utilisées.",
  desc: "Un site web présentant mes projets personnels, leur développement et les technologies utilisées pour chacun d'eux.",
  content: [
    "Mon Portfolio est une vitrine de mes projets personnels. Il est conçu pour refléter mes compétences en développement web, ainsi que ma capacité à résoudre des problématiques spécifiques à travers des solutions techniques adaptées. Chaque projet présenté contient une étude de cas détaillée, incluant la réflexion initiale, la conception, le développement et la mise en ligne.",
    "Le site utilise des technologies modernes comme React pour le front-end, Node.js pour le back-end, et est hébergé sur un serveur cloud pour une accessibilité optimale. Il présente un design épuré et une navigation intuitive.",
    "J'ai développé ce portfolio avec l'intention de mettre en avant mes projets les plus significatifs tout en assurant une présentation professionnelle et soignée. L'application est responsive, garantissant une expérience utilisateur fluide sur tous les appareils.",
    "Vous pouvez explorer mes projets en visitant le site via le lien ci-dessous.",
  ],
  technologies: [
    "React",
    "Node.js",
    "Tailwind",
    "JavaScript",
    "Git",
    "GitHub",
    "Figma",
  ],
    projectLink: "https://github.com/LeaBouillot/portfolio_lea.git",
  },
  {
    id: 4,
    img: "../assets/proj4.png",
    title: "Votre chef App",
    summary:
    "Votre Recette Cuisine est une application web dédiée aux passionnés de cuisine, permettant de rechercher, créer et partager des recettes de manière simple et interactive. Les utilisateurs peuvent ajouter leurs propres recettes, explorer celles des autres, et créer des listes de courses en un clic.",
  desc: "Une application web qui permet aux utilisateurs de découvrir, créer et partager des recettes culinaires facilement.",
  content: [
    "Votre Recette Cuisine est une plateforme de partage de recettes, permettant aux utilisateurs de trouver des idées de repas en fonction de leurs préférences. Les utilisateurs peuvent rechercher des recettes par ingrédient, type de plat ou régime alimentaire. De plus, ils peuvent ajouter leurs propres recettes, les organiser et les partager avec la communauté.",
    "L'application offre une fonctionnalité de liste de courses intégrée qui génère automatiquement les ingrédients nécessaires en fonction des recettes choisies. Une fois les recettes enregistrées, les utilisateurs peuvent consulter leurs listes de courses et les exporter pour faciliter leurs achats.",
    "Le développement de l'application utilise un back-end en Node.js avec une base de données MongoDB pour stocker les recettes et les utilisateurs. Le front-end est construit avec React, garantissant une interface interactive et responsive pour une expérience utilisateur optimale sur tous les appareils.",
    "N'hésitez pas à découvrir l'application et à consulter les recettes en suivant le lien ci-dessous.",
  ],
  technologies: [
    "React",
    "Node.js",
    "Tailwind",
    "JavaScript",
    "CSS3",
    "Git",
    "GitHub",
  ],
    projectLink: "https://github.com/LeaBouillot/votre-chef-app.git",
    site: "",
  },
  {
    id: 5,
    img: "../assets/proj5.png",
    title: "CodExpress",
    summary:
    "CodExpress est une application web conçue pour les développeurs, permettant de partager, organiser et découvrir des extraits de code. Elle facilite la collaboration en ligne et permet aux utilisateurs de stocker leurs morceaux de code pour une utilisation future.",
  desc: "Une plateforme en ligne où les développeurs peuvent partager, organiser et trouver des extraits de code rapidement.",
  content: [
    "CodExpress est une application web permettant aux développeurs de partager des extraits de code avec la communauté. Les utilisateurs peuvent télécharger leurs snippets, les organiser par catégories (langage de programmation, projet, etc.), et les étiqueter pour faciliter la recherche.",
    "L'application propose également un moteur de recherche puissant qui permet de trouver facilement des morceaux de code en fonction des mots-clés, du langage ou de la catégorie. Les utilisateurs peuvent commenter, évaluer et adapter les snippets des autres pour les intégrer à leurs propres projets.",
    "L'architecture de CodExpress repose sur un back-end en Node.js avec une base de données MongoDB pour stocker les extraits de code et les profils des utilisateurs. Le front-end est développé avec React, offrant une interface fluide et responsive, adaptée à tous les appareils.",
    "Découvrez la plateforme CodExpress et partagez vos propres extraits de code en visitant le lien ci-dessous.",
  ],
    technologies: ["Symfony7","Twig", "Tailwind", "JavaScript", "MySql", "GIT", "Github"],
    projectLink: "https://github.com/LeaBouillot/codexpress.git",
    site: "https://codexpress.leabouillot.top",
  },
  {
    id: 6,
    img: "../assets/proj6.png",
    title: "Patatrucs",
    summary:
    "Patatrucs est un atelier de stop-motion pour enfants, leur permettant d'explorer leur créativité en réalisant des animations à partir de leurs propres créations. Ce projet vise à initier les enfants aux techniques d'animation tout en leur offrant un moyen ludique de raconter des histoires.",
  desc: "Un atelier de stop-motion interactif conçu pour les enfants, pour les aider à créer leurs propres animations et stimuler leur imagination.",
  content: [
    "Patatrucs est un atelier d'animation stop-motion conçu pour les enfants, où ils peuvent créer leurs propres animations en manipulant des objets et personnages en pâte à modeler. L'application fournit une interface simple et intuitive qui permet aux enfants de capturer chaque mouvement et de voir instantanément leur animation prendre vie.",
    "Les enfants peuvent choisir des scénarios prédéfinis ou créer leurs propres histoires, tout en apprenant les bases de l'animation et de la narration visuelle. Des outils intuitifs permettent de contrôler la vitesse, d'ajouter des effets sonores et de partager leurs créations.",
    "Le projet utilise une combinaison d'une plateforme web et d'une application mobile pour offrir une expérience immersive. L'interface est conçue avec des couleurs vives et des interactions ludiques pour captiver l'attention des plus jeunes. Le back-end est construit avec Node.js pour une gestion fluide des projets créés par les utilisateurs.",
    "Patatrucs vise à offrir aux enfants un espace où ils peuvent exprimer leur créativité tout en apprenant une compétence technique intéressante. Découvrez cet atelier en visitant le lien ci-dessous.",
  ],
    technologies: ["Wordpress"],
    projectLink: "https://myprojetweb.top",
    site: "https://myprojetweb.top",
  },
  {
    id: 7,
    img: "../assets/proj7.png",
    title: "To do App",
    summary:
    "To do App est une application web simple et efficace pour la gestion des tâches quotidiennes. Elle permet aux utilisateurs de créer, organiser et suivre leurs tâches, tout en offrant des fonctionnalités de rappel et de priorisation pour mieux gérer leur emploi du temps.",
  desc: "Une application web permettant de créer et de gérer facilement des listes de tâches à accomplir.",
  content: [
    "To do App est une application web dédiée à la gestion des tâches. Les utilisateurs peuvent ajouter des tâches, définir des priorités, attribuer des dates limites et marquer les tâches comme complètes. L'application offre également la possibilité de filtrer les tâches par statut, priorité ou date.",
    "Les utilisateurs peuvent personnaliser leur expérience avec des fonctionnalités comme la gestion des catégories et des sous-tâches, et recevoir des rappels pour les échéances à venir. L'application est conçue pour être simple et intuitive, avec une interface épurée pour une utilisation optimale.",
    "L'application utilise React pour le front-end, avec une gestion d'état via Redux pour suivre les modifications des tâches en temps réel. Le back-end est construit avec Node.js et une base de données MongoDB pour stocker les informations sur les utilisateurs et les tâches.",
    "Essayez l'application pour découvrir une méthode simple et efficace pour organiser vos journées et ne rien oublier.",
  ],
    technologies: ["React", "JavaScript", "Tailwind", "GIT", "Github"],
    projectLink: "https://github.com/LeaBouillot/Todo-app-react.git",
    site: "",
  },
  {
    id: 8,
    img: "../assets/proj8.png",
    title: "CamSense",
    summary:
    "CamSense est une application web développée lors d'un CamSense, permettant la reconnaissance d'objets en temps réel grâce à l'IA. L'application utilise des techniques de vision par ordinateur pour identifier et afficher des objets à partir de la caméra de l'utilisateur, le tout avec une interface simple et réactive.",
  desc: "Une application de reconnaissance d'objets en temps réel utilisant la vision par ordinateur, développée en JavaScript et CSS.",
  content: [
    "CamSense est une application de reconnaissance d'objets en temps réel, utilisant l'intelligence artificielle pour analyser les images capturées par la caméra. L'application identifie les objets et les affiche à l'utilisateur, tout en fournissant des informations détaillées sur chaque élément détecté.",
    "L'application est développée en JavaScript et CSS pour l'interface utilisateur, offrant une expérience fluide et réactive. Le projet utilise des bibliothèques comme TensorFlow.js pour la reconnaissance d'objets et des algorithmes de vision par ordinateur pour analyser les images en temps réel.",
    "L'interface est simple, avec une fenêtre de caméra en direct et une zone où les objets détectés sont listés avec des informations supplémentaires. Le projet a été conçu pour être intuitif, rapide et interactif, offrant une démonstration directe de la reconnaissance d'objets.",
    "Découvrez cette application innovante en consultant le lien ci-dessous.",
  ],
  technologies: [
    "JavaScript",
    "CSS3",
    "TensorFlow.js",
    "HTML5",
    "Git",
    "GitHub",
  ],
    projectLink: "https://github.com/LeaBouillot/Projet_Hackathon.git",
    site: "https://hackathon-objets.netlify.app",
  },
];
